---
# defaults variables file for build_docker role
# local ip for DevTools instance
NEXUS_SERVER_IP: {{ devtools_aws_server_local }}
NEXUS_SERVER_PORT: 8081
NEXUS_DOCKER_PORT: 5000
MAVEN_REPOSITORY: maven-repository
MAVEN_LOGIN: dell
MAVEN_PASSWORD: 159632
MAVEN_GROUPID: java
MAVEN_ARTIFACTID: spring-boot-smoke-test-web-ui
MAVEN_EXTENTION: jar

DOCKER_GROUP: docker
DOCKER_USER: docker
DOCKER_IMAGE_NAME: javapp

JAVAAPP_SERVICE_PORT: 8080

BUILD_NUMBER: "{{ lookup('file', '/var/lib/jenkins/build.number', errors='warn') }}"
